### ISSUE TITLE
Fix  EagerVariableNameReuse error

### ISSUE THREAD

**Issue by ndiamant** [broadinstitute/ml4h#221]
**What**
When trying to train and having a notebook open that imports `TMAPS` you get error:
```python
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse
```
This issue is to fix that error.

**Why**
It is annoying to have to shut down notebooks to train a model. 

**How**
I have no idea how this error is possible. Shouldn't different python processes have different globals? This would take a little research to solve. First step would be a quick way to reproduce the error.

**Acceptance Criteria**
It is possible to import TMAPS in multiple processes on the same machine.

**Comment by lucidtronix** [comment]
done this is just GPU running out of memory
